#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 input.bf output.s"
    echo
    echo "To compile assembly output:"
    echo "clang -o output output.s shim.a"
    exit 1
fi

./llvm-brainfuck < $1 | llvm-as | opt -instcombine | llc > $2
